name: Decision Log Automation
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed]
    paths:
      - "adr/*.md"

jobs:
  decision-log:
    if: ${{ github.event.review.state == 'approved' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Write decision to decision-log.md file
        run: |
          echo "----------------------------------------" >> decision-log/decision-log.md
          echo "Decision made in pull request review: ${{ github.event.review.body }}" >> decision-log/decision-log.md
          echo "Decision made by: ${{ github.event.review.user.login }}" >> decision-log/decision-log.md
          echo "Decision made on: ${{ github.event.review.submitted_at }}" >> decision-log/decision-log.md
          echo "----------------------------------------" >> decision-log/decision-log.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add decision-log/decision-log.md
          git commit -m "Update decision log with new approval"
          git push
