name: Decision Log Automation
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  decision-log:
    runs-on: ubuntu-latest
    steps:
      - name: Write decision to decision-log readmefile file
        run: |
          // add status of adr to decision-log.md file
          echo "----------------------------------------" >> decision-log.md
          echo "Decision made in pull request review: ${{ github.event.review.body }}" >> decision-log.nd
          echo "Decision made by: ${{ github.event.review.user.login }}" >> decision-log.md
          echo "Decision made on: ${{ github.event.review.submitted_at }}" >> decision-log.md
          echo "----------------------------------------" >> decision-log.md
